"use client";

import {
  AlertTriangle,
  BookOpen,
  CheckCircle2,
  ExternalLink,
  Info,
  ShieldCheck,
  Sparkles,
} from "lucide-react";
import Link from "next/link";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import type { RecommendResponse } from "@/lib/api";
import { formatMs } from "@/lib/format";
import { cn } from "@/lib/utils";

/**
 * The RAG answer, with the things that make it trustworthy attached to it:
 * every citation, every warning, and the mode that produced it.
 *
 * `mode` is shown as a badge and not hidden. "extractive" means the answer is
 * assembled from retrieved clauses and quotes the corpus; "llm" means a model
 * wrote it. Those deserve different amounts of trust, and a UI that renders
 * both identically is asking the user to guess.
 */
export function AnswerPanel({ answer }: { answer: RecommendResponse }) {
  const isLlm = answer.mode === "llm";

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <CardTitle className="flex items-center gap-2 text-base">
            {isLlm ? (
              <Sparkles className="h-4 w-4 text-tricolor-saffron" />
            ) : (
              <BookOpen className="h-4 w-4 text-tricolor-saffron" />
            )}
            Answer
          </CardTitle>
          <div className="flex flex-wrap items-center gap-2">
            <Badge variant={isLlm ? "default" : "outline"}>
              {isLlm ? "Generated by LLM" : "Extracted from the standards"}
            </Badge>
            {answer.grounded ? (
              <Badge variant="success" className="gap-1">
                <CheckCircle2 className="h-3 w-3" />
                Every citation verified
              </Badge>
            ) : (
              <Badge variant="warning" className="gap-1">
                <AlertTriangle className="h-3 w-3" />
                Unverified citations
              </Badge>
            )}
            <span className="text-xs text-muted-foreground">{formatMs(answer.took_ms)}</span>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        <div className="whitespace-pre-line text-sm leading-relaxed">{answer.answer}</div>

        {answer.unsupported_citations.length > 0 ? (
          <div className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">
            <p className="flex items-center gap-2 font-medium">
              <AlertTriangle className="h-4 w-4" />
              Citations the corpus does not contain
            </p>
            <p className="mt-1">
              A generated answer mentioned {answer.unsupported_citations.join(", ")}. These were
              not found in the dataset and are <strong>not</strong> verified — check them against
              the BIS catalogue before relying on them.
            </p>
          </div>
        ) : null}

        {answer.citations.length > 0 ? (
          <>
            <Separator />
            <div className="space-y-2">
              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Sources ({answer.citations.length})
              </p>
              <ul className="grid gap-2 sm:grid-cols-2">
                {answer.citations.map((citation) => (
                  <li
                    key={citation.designation + citation.chunk_id}
                    className="rounded-lg border bg-muted/30 p-3"
                  >
                    <div className="flex items-start justify-between gap-2">
                      <Link
                        href={`/standards?q=${encodeURIComponent(citation.designation)}`}
                        className="font-mono text-sm font-semibold hover:text-tricolor-saffron hover:underline"
                      >
                        {citation.designation}
                      </Link>
                      {citation.is_current ? (
                        <Badge variant="success">Current</Badge>
                      ) : (
                        <Badge variant="warning">Superseded</Badge>
                      )}
                    </div>
                    <p className="mt-1 text-xs leading-snug text-muted-foreground">
                      {citation.title}
                    </p>
                    {citation.superseded_by ? (
                      <p className="mt-1 text-xs text-amber-700">
                        Replaced by {citation.superseded_by}
                      </p>
                    ) : null}
                    {citation.archive_url ? (
                      <a
                        href={citation.archive_url}
                        target="_blank"
                        rel="noreferrer noopener"
                        className="mt-1 inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground hover:underline"
                      >
                        Source document <ExternalLink className="h-3 w-3" />
                      </a>
                    ) : null}
                  </li>
                ))}
              </ul>
            </div>
          </>
        ) : null}

        {answer.warnings.length > 0 ? (
          <div className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">
            <p className="flex items-center gap-2 font-medium">
              <AlertTriangle className="h-4 w-4" />
              Warnings
            </p>
            <ul className="mt-1 list-disc space-y-0.5 pl-5">
              {answer.warnings.map((warning) => (
                <li key={warning}>{warning}</li>
              ))}
            </ul>
          </div>
        ) : null}

        {answer.compliance ? (
          <div className="rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900">
            <p className="flex items-center gap-2 font-medium">
              <ShieldCheck className="h-4 w-4" />
              Compliance check attached: {answer.compliance.grade} (
              {Math.round(answer.compliance.compliance_score * 100)}/100)
            </p>
            <Link href="/compliance" className="mt-1 inline-block underline">
              Open the full gap report
            </Link>
          </div>
        ) : null}

        {answer.notes.length > 0 ? (
          <details className="rounded-md border bg-muted/30 p-3 text-xs text-muted-foreground">
            <summary className="flex cursor-pointer items-center gap-2 font-medium text-foreground">
              <Info className="h-3.5 w-3.5" />
              How this answer was produced ({answer.notes.length} steps)
            </summary>
            <ul className={cn("mt-2 list-disc space-y-1 pl-5")}>
              {answer.notes.map((note) => (
                <li key={note}>{note}</li>
              ))}
            </ul>
          </details>
        ) : null}
      </CardContent>
    </Card>
  );
}
