"""Facts about the corpus, the vector store and the environment.

``bis-rag doctor`` prints this; the evaluator gates on it. It lives in its own
module so the two cannot disagree: the CLI once built its own picture of the
corpus and reported "197 standards" on a 12-standard fixture, which is the sort
of number people quote in a report.

The important export is :func:`inspect_provenance`. A synthetic fixture is
useful for tests and actively dangerous in an evaluation, because a hit rate
computed over twelve hand-picked standards where the case file was written to
match them is not evidence about anything. So a fixture has to announce itself
(both the generator and this module know the marker filename), and
:func:`require_real_corpus` refuses to certify one.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from .data import BisData
from .vectorstore import COLLECTION_FOR, available_backends, detect_backend

#: Written by ``tests/synth_bis_data.py``. Its presence means the corpus is
#: generated, not scraped, and every number derived from it is illustrative.
FIXTURE_MARKER = ".synthetic_fixture.json"

#: A corpus below this many standards cannot be the real one (197 standards).
#: It is a floor for *certification*, not a validity check: a partial corpus is
#: a perfectly good corpus to develop against, just not to quote a hit rate
#: from. Set far below 197 so a genuinely partial scrape still passes.
MIN_PRODUCTION_STANDARDS = 50


class FixtureDataError(RuntimeError):
    """Raised when fixture data would be reported as a real measurement."""


@dataclass
class CollectionFacts:
    name: str
    level: str
    count: Optional[int] = None
    backend: str = ""
    error: str = ""

    @property
    def ok(self) -> bool:
        return self.count is not None and not self.error


@dataclass
class StoreFacts:
    path: Path
    exists: bool = False
    backend: str = ""
    embedder_name: str = ""
    embedder_fingerprint: str = ""
    dim: Optional[int] = None
    collections: list[CollectionFacts] = field(default_factory=list)
    error: str = ""

    @property
    def total_vectors(self) -> int:
        return sum(c.count or 0 for c in self.collections)


@dataclass
class CorpusFacts:
    root: Path
    exists: bool = False
    standards: int = 0
    chunks: int = 0
    divisions: int = 0
    committees: int = 0
    current: int = 0
    superseded: int = 0
    compulsory: int = 0
    year_range: tuple[int, int] = (0, 0)
    tfidf_index: bool = False
    error: str = ""

    @property
    def superseded_share(self) -> float:
        return (self.superseded / self.standards) if self.standards else 0.0


@dataclass
class ProvenanceFacts:
    """Where the corpus came from, so nobody has to guess."""

    root: Path
    is_fixture: bool = False
    marker: Optional[Path] = None
    detail: dict[str, Any] = field(default_factory=dict)
    #: True when the corpus is too small to be the real one even though no
    #: marker was found -- an old fixture, a truncated copy, or a partial scrape.
    suspiciously_small: bool = False
    standards: int = 0

    @property
    def kind(self) -> str:
        if self.is_fixture:
            return "synthetic fixture"
        if self.suspiciously_small:
            return "unverified small corpus"
        return "real corpus"

    @property
    def certifiable(self) -> bool:
        """Whether numbers from this corpus may be called production accuracy."""
        return not self.is_fixture and not self.suspiciously_small

    def as_dict(self) -> dict[str, Any]:
        return {
            "root": str(self.root),
            "kind": self.kind,
            "is_fixture": self.is_fixture,
            "marker": str(self.marker) if self.marker else None,
            "suspiciously_small": self.suspiciously_small,
            "certifiable_as_production": self.certifiable,
            "standards": self.standards,
            "detail": self.detail,
        }

    def warning(self) -> str:
        if self.is_fixture:
            return (
                f"SYNTHETIC FIXTURE DATA at {self.root}: "
                f"{self.detail.get('standards', '?')} standards generated by "
                f"{self.detail.get('generator', 'the test helper')}. Every number "
                f"below describes the fixture, not the retrieval engine and not "
                f"the 197-standard corpus. Do not report it as production accuracy."
            )
        if self.suspiciously_small:
            return (
                f"this corpus holds only {self.standards} standards, below the "
                f"{MIN_PRODUCTION_STANDARDS}-standard floor for certification. "
                f"It is usable for development; it is not the full corpus."
            )
        return ""


# ----------------------------------------------------------------------
# inspectors
# ----------------------------------------------------------------------
def inspect_provenance(data: BisData, standards: Optional[int] = None) -> ProvenanceFacts:
    """Read the fixture marker, if there is one."""
    root = Path(data.root)
    marker = root / FIXTURE_MARKER
    facts = ProvenanceFacts(root=root)
    if marker.exists():
        facts.is_fixture = True
        facts.marker = marker
        try:
            loaded = json.loads(marker.read_text(encoding="utf-8"))
            facts.detail = loaded if isinstance(loaded, dict) else {}
        except (json.JSONDecodeError, OSError):
            facts.detail = {"generator": "unknown (marker unreadable)"}

    if standards is None:
        try:
            standards = len(data.standards())
        except Exception:  # noqa: BLE001 - provenance must never be the thing that fails
            standards = 0
    facts.standards = standards
    facts.suspiciously_small = standards > 0 and standards < MIN_PRODUCTION_STANDARDS
    return facts


def inspect_corpus(data: BisData) -> CorpusFacts:
    """Count what is actually on disk, or record why it cannot be counted."""
    root = Path(data.root)
    facts = CorpusFacts(root=root, exists=root.exists())
    try:
        standards = data.standards()
    except Exception as exc:  # noqa: BLE001
        facts.error = str(exc)
        return facts
    try:
        facts.chunks = len(data.chunks())
    except Exception as exc:  # noqa: BLE001
        facts.error = str(exc)
    facts.standards = len(standards)
    facts.divisions = len({s.division for s in standards if getattr(s, "division", "")})
    facts.committees = len({s.committee for s in standards if getattr(s, "committee", "")})
    facts.current = sum(1 for s in standards if getattr(s, "is_current", True))
    facts.superseded = facts.standards - facts.current
    facts.compulsory = sum(1 for s in standards if getattr(s, "is_compulsory", False))
    years = [s.year for s in standards if getattr(s, "year", None)]
    facts.year_range = (min(years), max(years)) if years else (0, 0)
    facts.tfidf_index = data.tfidf_index() is not None
    return facts


def inspect_store(store_dir: Path | str, *, backend: str = "auto") -> StoreFacts:
    """Count vectors per collection, without importing an optional backend."""
    path = Path(store_dir).expanduser()
    facts = StoreFacts(path=path, exists=path.exists())
    if not facts.exists:
        facts.error = "does not exist"
        return facts

    # store_meta.json is written by the builder and names the backend and the
    # embedder, so the store can be described without opening it.
    meta_file = path / "store_meta.json"
    if meta_file.exists():
        try:
            meta = json.loads(meta_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            facts.error = f"unreadable store_meta.json ({exc})"
            meta = {}
        if isinstance(meta, dict):
            embedder = meta.get("embedder") or {}
            if isinstance(embedder, dict):
                facts.embedder_name = str(embedder.get("name") or "")
                facts.embedder_fingerprint = str(embedder.get("fingerprint") or "")
                dim = embedder.get("dim")
                facts.dim = int(dim) if isinstance(dim, (int, float)) else None

    detected = detect_backend(path, COLLECTION_FOR["chunks"]) or \
        detect_backend(path, COLLECTION_FOR["standards"])
    facts.backend = detected or ("unknown" if backend == "auto" else backend)

    from .vectorstore import open_store

    for level, collection in COLLECTION_FOR.items():
        entry = CollectionFacts(name=collection, level=level)
        try:
            store = open_store(path, collection, backend=backend, create=False)
            entry.count = store.count()
            entry.backend = store.backend
            if not facts.embedder_name:
                # The json backend records the embedder per collection rather
                # than once for the store, so without this the report says
                # "embedder: unrecorded" for a store that does record it.
                meta = store.get_meta()
                embedder = meta.get("embedder") or {}
                if isinstance(embedder, dict):
                    facts.embedder_name = str(embedder.get("name") or "")
                    facts.embedder_fingerprint = str(embedder.get("fingerprint") or "")
                    dim = embedder.get("dim")
                    facts.dim = int(dim) if isinstance(dim, (int, float)) else None
        except Exception as exc:  # noqa: BLE001
            entry.error = str(exc)
        facts.collections.append(entry)
    return facts


# ----------------------------------------------------------------------
# the gate
# ----------------------------------------------------------------------
def require_real_corpus(data: BisData, *, what: str = "evaluation",
                        allow_fixture: bool = False,
                        standards: Optional[int] = None) -> ProvenanceFacts:
    """Refuse to certify fixture data as a measurement.

    Raises :class:`FixtureDataError` with a message that says what was found and
    what to do about it, rather than a bare "invalid data".
    """
    facts = inspect_provenance(data, standards=standards)
    if allow_fixture or facts.certifiable:
        return facts

    if facts.is_fixture:
        raise FixtureDataError(
            f"{what} was asked for --production, but {facts.root} is a synthetic "
            f"fixture: {facts.detail.get('standards', facts.standards)} generated "
            f"standards ({facts.marker.name}). A hit rate over a corpus this small, "
            f"with a case file written to match it, is not evidence about the "
            f"retrieval engine. Point --data-dir at the scraped bis_data/ "
            f"(197 standards), or drop --production to report fixture numbers as "
            f"fixture numbers."
        )
    raise FixtureDataError(
        f"{what} was asked for --production, but {facts.root} holds only "
        f"{facts.standards} standards, below the {MIN_PRODUCTION_STANDARDS}-standard "
        f"floor. This is what a partial scrape or a leftover fixture looks like. "
        f"Point --data-dir at the full corpus, or drop --production."
    )


# ----------------------------------------------------------------------
# rendering
# ----------------------------------------------------------------------
def doctor_payload(corpus: CorpusFacts, store: StoreFacts,
                   provenance: ProvenanceFacts, *, embedder: str = "",
                   backends: Optional[list[str]] = None) -> dict[str, Any]:
    """Everything doctor prints, as data, so the artifacts can carry it too."""
    return {
        "data_dir": str(corpus.root),
        "store_dir": str(store.path),
        "corpus": {
            "exists": corpus.exists,
            "standards": corpus.standards,
            "chunks": corpus.chunks,
            "divisions": corpus.divisions,
            "committees": corpus.committees,
            "current": corpus.current,
            "superseded": corpus.superseded,
            "compulsory": corpus.compulsory,
            "year_range": list(corpus.year_range),
            "tfidf_index": corpus.tfidf_index,
            "error": corpus.error,
        },
        "vector_store": {
            "path": str(store.path),
            "exists": store.exists,
            "backend": store.backend,
            "embedder": store.embedder_name,
            "fingerprint": store.embedder_fingerprint,
            "dim": store.dim,
            "total_vectors": store.total_vectors,
            "collections": [
                {"name": c.name, "level": c.level, "count": c.count,
                 "backend": c.backend, "error": c.error}
                for c in store.collections
            ],
        },
        "embedder_requested": embedder,
        "available_backends": backends if backends is not None else available_backends(),
        "provenance": provenance.as_dict(),
    }


def format_doctor(payload: dict[str, Any]) -> str:
    """Render :func:`doctor_payload` for a terminal."""
    corpus = payload["corpus"]
    store = payload["vector_store"]
    provenance = payload["provenance"]
    lines: list[str] = ["bis-rag doctor", ""]

    kind = provenance["kind"]
    # With no directory at all, "REAL CORPUS" was the one thing the banner must
    # not say: the absence of a fixture is not the presence of data.
    if not corpus["exists"]:
        kind = "no corpus"
    banner = f"  PROVENANCE : {kind.upper()}"
    if provenance["is_fixture"]:
        banner = f"  PROVENANCE : {kind.upper()}  <- NOT PRODUCTION DATA"
    lines += [banner,
              f"  data dir   : {payload['data_dir']}",
              f"  store dir  : {payload['store_dir']}", ""]
    if provenance["marker"]:
        lines.append(f"  fixture marker: {provenance['marker']}")
        generator = (provenance.get("detail") or {}).get("generator")
        if generator:
            lines.append(f"  generated by  : {generator}")
        lines.append("")

    lines.append("Corpus")
    if not corpus["exists"]:
        lines.append("  data directory does not exist")
    elif corpus["error"]:
        lines.append(f"  unreadable: {corpus['error']}")
    else:
        lines.append(f"  standards        {corpus['standards']}")
        lines.append(f"  chunks           {corpus['chunks']}")
        lines.append(f"  divisions        {corpus['divisions']}")
        lines.append(f"  committees       {corpus['committees']}")
        lines.append(f"  current          {corpus['current']}")
        lines.append(f"  superseded       {corpus['superseded']}")
        lines.append(f"  compulsory       {corpus['compulsory']}")
        low, high = corpus["year_range"]
        lines.append(f"  year range       {low}-{high}" if low else "  year range       unknown")
        lines.append(f"  tf-idf index     {'present' if corpus['tfidf_index'] else 'absent'}")

    lines += ["", "Vector store"]
    if not store["exists"]:
        lines.append(f"  {store['path']} does not exist -- run `bis-rag build`")
    else:
        lines.append(f"  backend          {store['backend']}")
        lines.append(f"  embedder         {store['embedder'] or 'unrecorded'}"
                     + (f" (dim={store['dim']})" if store["dim"] else ""))
        if store["fingerprint"]:
            lines.append(f"  fingerprint      {store['fingerprint']}")
        lines.append(f"  collections      {len(store['collections'])}"
                     f"   total vectors {store['total_vectors']}")
        for collection in store["collections"]:
            if collection["error"]:
                lines.append(f"    {collection['name']:<16} (level={collection['level']})"
                             f"  unavailable: {collection['error']}")
            else:
                lines.append(f"    {collection['name']:<16} (level={collection['level']})"
                             f"  {collection['count']} vectors")

    lines += ["", "Environment",
              f"  embedder requested : {payload['embedder_requested'] or '(config default)'}",
              f"  store backends     : {', '.join(payload['available_backends'])}"]

    warning = provenance.get("warning") or _provenance_warning(provenance)
    if warning:
        lines += ["", "WARNING:", "  " + warning.replace("\n", "\n  ")]
    return "\n".join(lines) + "\n"


def _provenance_warning(provenance: dict[str, Any]) -> str:
    if provenance.get("is_fixture"):
        return (f"synthetic fixture: {provenance.get('standards')} generated standards. "
                f"Numbers from this corpus describe the fixture, not the engine.")
    if provenance.get("suspiciously_small"):
        return (f"only {provenance.get('standards')} standards, below the "
                f"{MIN_PRODUCTION_STANDARDS}-standard floor for certification.")
    return ""
